In [31]:
import numpy as np
import pandas as pd

from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

from sklearn.metrics import accuracy_score ,mean_squared_error, r2_score, mean_absolute_error

In [32]:
data = fetch_california_housing(as_frame = True)

In [33]:
data1 = data.frame

In [34]:
data1

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422
...,...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09,0.781
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21,0.771
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22,0.923
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32,0.847
20639,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24,0.894

In [35]:
data

{'data':        MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
 0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88
 1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86
 2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85
 3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85
 4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85
 ...       ...       ...       ...        ...         ...       ...       ...
 20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48
 20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49
 20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43
 20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43
 20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37

        Longitude
 0        -122.23
 1        -122.22
 2        -122.24
 3        -122.25
 4        -122.25
 ...          ...
 20635    -121.09
 20636    -121.21
 20637    -121.22
 20638    -121.32
 20639    -121.24

 [20640 rows x 8 columns],
 'target': 0        4.526
 1        3.585
 2        3.521
 3        3.413
 4        3.422
          ...
 20635    0.781
 20636    0.771
 20637    0.923
 20638    0.847
 20639    0.894
 Name: MedHouseVal, Length: 20640, dtype: float64,
 'frame':        MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
 0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88
 1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86
 2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85
 3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85
 4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85
 ...       ...       ...       ...        ...         ...       ...       ...
 20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48
 20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49
 20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43
 20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43
 20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37

        Longitude  MedHouseVal
 0        -122.23        4.526
 1        -122.22        3.585
 2        -122.24        3.521
 3        -122.25        3.413
 4        -122.25        3.422
 ...          ...          ...
 20635    -121.09        0.781
 20636    -121.21        0.771
 20637    -121.22        0.923
 20638    -121.32        0.847
 20639    -121.24        0.894

 [20640 rows x 9 columns],
 'target_names': ['MedHouseVal'],
 'feature_names': ['MedInc',
  'HouseAge',
  'AveRooms',
  'AveBedrms',
  'Population',
  'AveOccup',
  'Latitude',
  'Longitude'],
 'DESCR': '.. _california_housing_dataset:\n\nCalifornia Housing dataset\n--------------------------\n\n**Data Set Characteristics:**\n\n:Number of Instances: 20640\n\n:Number of Attributes: 8 numeric, predictive attributes and the target\n\n:Attribute Information:\n    - MedInc        median income in block group\n    - HouseAge      median house age in block group\n    - AveRooms      average number of rooms per household\n    - AveBedrms     average number of bedrooms per household\n    - Population    block group population\n    - AveOccup      average number of household members\n    - Latitude      block group latitude\n    - Longitude     block group longitude\n\n:Missing Attribute Values: None\n\nThis dataset was obtained from the StatLib repository.\nhttps://www.dcc.fc.up.pt/~ltorgo/Regression/cal_housing.html\n\nThe target variable is the median house value for California districts,\nexpressed in hundreds of thousands of dollars ($100,000).\n\nThis dataset was derived from the 1990 U.S. census, using one row per census\nblock group. A block group is the smallest geographical unit for which the U.S.\nCensus Bureau publishes sample data (a block group typically has a population\nof 600 to 3,000 people).\n\nA household is a group of people residing within a home. Since the average\nnumber of rooms and bedrooms in this dataset are provided per household, these\ncolumns may take surprisingly large values for block groups with few households\nand many empty houses, such as vacation resorts.\n\nIt can be downloaded/loaded using the\n:func:`sklearn.datasets.fetch_california_housing` function.\n\n.. rubric:: References\n\n- Pace, R. Kelley and Ronald Barry, Sparse Spatial Autoregressions,\n  Statistics and Probability Letters, 33:291-297, 1997.\n'}

In [36]:
X = data.data
y = data.target

In [37]:
X

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25
...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32
20639,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24

In [38]:
X = data.data
y = data.target

In [39]:
y

0        4.526
1        3.585
2        3.521
3        3.413
4        3.422
         ...
20635    0.781
20636    0.771
20637    0.923
20638    0.847
20639    0.894
Name: MedHouseVal, Length: 20640, dtype: float64

In [40]:
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import(
RandomForestRegressor,
GradientBoostingRegressor,
ExtraTreesRegressor
)
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import SVR
from sklearn.neural_network import MLPRegressor

In [41]:
models = {
    "Linear Regression": LinearRegression(),
    "Ridge Regression": Ridge(alpha=1.0),
    "Lasso": Lasso(alpha=1.0),
    "Decision Tree": DecisionTreeRegressor(),
    "Random Forest": RandomForestRegressor(n_estimators=100),
    "ExtraTree": ExtraTreesRegressor(n_estimators=100),
    "Gradient Boosting": GradientBoostingRegressor(),
    "KNN": KNeighborsRegressor(n_neighbors=5),
    "SVR": SVR(),
    "Neural Network": MLPRegressor(hidden_layer_sizes=(100, 50), max_iter=500)
}

In [42]:
print(type(models))

<class 'dict'>

In [43]:
models

{'Linear Regression': LinearRegression(),
 'Ridge Regression': Ridge(),
 'Lasso': Lasso(),
 'Decision Tree': DecisionTreeRegressor(),
 'Random Forest': RandomForestRegressor(),
 'ExtraTree': ExtraTreesRegressor(),
 'Gradient Boosting': GradientBoostingRegressor(),
 'KNN': KNeighborsRegressor(),
 'SVR': SVR(),
 'Neural Network': MLPRegressor(hidden_layer_sizes=(100, 50), max_iter=500)}

In [44]:
 X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [45]:
import pandas as pd

results = []

for name, model in models.items():

    pipeline = Pipeline([
        ("scaler", StandardScaler()),
        ("model", model)
    ])

    pipeline.fit(X_train, y_train)

    preds = pipeline.predict(X_test)

    mae = mean_absolute_error(y_test, preds)
    mse = mean_squared_error(y_test, preds)
    rmse = np.sqrt(mse)
    r2 = r2_score(y_test, preds)

    n = X_test.shape[0]
    p = X_test.shape[1]
    adj_r2 = 1 - ((1 - r2) * (n - 1) / (n - p - 1))

    results.append([name, mae, mse, rmse, r2, adj_r2])

# Create DataFrame
results_df = pd.DataFrame(
    results,
    columns=[
        "Model",
        "MAE",
        "MSE",
        "RMSE",
        "R2 Score",
        "Adjusted R2"
    ]
)

In [46]:
results_df = results_df.sort_values(by="R2 Score", ascending=False)

In [47]:
results_df

               Model       MAE       MSE      RMSE  R2 Score  Adjusted R2
5          ExtraTree  0.333533  0.260821  0.510706  0.804276     0.804046
4      Random Forest  0.335818  0.261838  0.511701  0.803512     0.803281
9     Neural Network  0.350553  0.267378  0.517086  0.799355     0.799119
6  Gradient Boosting  0.373818  0.292702  0.541019  0.780352     0.780093
8                SVR  0.399135  0.357262  0.597714  0.731904     0.731589
7                KNN  0.450267  0.440196  0.663473  0.669669     0.669281
1   Ridge Regression  0.529567  0.536946  0.732766  0.597067     0.596593
0  Linear Regression  0.529571  0.536969  0.732781  0.597049     0.596576
3      Decision Tree  0.474603  0.542703  0.736684  0.592746     0.592268
2              Lasso  0.912651  1.332626  1.154394 -0.000025    -0.001201